apiVersion: v1
kind: Service
metadata:
  name: minikube-price-service
  labels:
    app: minikube-price-service
spec:
  type: NodePort
  ports:
    - port: 8089
      protocol: TCP
      targetPort: 8089
  selector:
    app: minikube-price-service