apiVersion: v1
kind: Service
metadata:
  name: minikube-price-service-redis
spec:
  selector:
    app: minikube-price-service-redis
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 6379