apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-price-service-redis
spec:
  selector:
    matchLabels:
      app: minikube-price-service-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: minikube-price-service-redis
    spec:
      containers:
        - name: service-redis
          image: redis:latest